version: "2"

services:
  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-alpha
    container_name: influxdb
    hostname: influxdb
    ports:
      - "9999:9999"
    environment:
      - INFLUX_DB=telegraf
    volumes:
      - $PWD/influxdb-store:/root/.influxdbv2
    restart: always

  proxyneta:
    build: ./server/
    container_name: proxyneta
    hostname: proxyneta
    ports:
      - "3333:3333"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    env_file:
      - "env.grafana"
    user: "0"
    links:
      - influxdb
      - proxyneta
    volumes:
      - $PWD/grafana-store:/var/lib/grafana
    restart: always
