version: "2"

services:
  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-alpha
    container_name: influxdb
    hostname: influxdb
    ports:
      - "9999:9999"
    environment:
      - INFLUX_DB=telegraf
    volumes:
      - $PWD/influxdb-store:/root/.influxdbv2
    restart: always

  proxyneta:
    build: ./server/
    container_name: proxyneta
    hostname: proxyneta
    ports:
      - "3333:3333"
    restart: always
