influxdb:
  image: quay.io/influxdb/influxdb:2.0.0-alpha
  container_name: influxdb
  hostname: influxdb
  ports:
     - "9999:9999"
  environment:
      - INFLUX_DB=telegraf
  volumes:
      - $PWD:/var/lib/influxdb

telegraf:
  image: telegraf:latest
  container_name: telegraf
  hostname: telegraf
  links:
     - influxdb
     - bitmex
     - proxyneta
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

bitmex:
  build: ./docker-bitmex-delta-server/
  container_name: bitmex-delta-server
  hostname: bitmex
  ports:
    - "4444:4444"

proxyneta:
  build: ./proxyneta/
  container_name: proxyneta
  hostname: proxyneta
  ports:
    - "3333:3333"

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  hostname: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  user: "0"
  links:
    - influxdb
    - telegraf
    - bitmex
    - proxyneta
  volumes:
    - $PWD:/var/lib/grafana
